CREATE OR REPLACE PROCEDURE SALES_DEV.COMMON.GET_ACCOUNT_REGION_CLOUD()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    result VARCHAR;
BEGIN
    SELECT CURRENT_REGION() INTO result;
    RETURN result;
END;
$$;
