-- DDL for SAMPLE_TABLE and SAMPLE_PROCEDURE across all OAD and PSD project schemas
-- Co-authored with CoCo

create or replace TABLE CNTRL_ITSS_OAD_DEV_DB.OAD_AUDITZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_DEV_DB.OAD_AUDITZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_DEV_DB.OAD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_DEV_DB.OAD_CONZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_DEV_DB.OAD_CONZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_DEV_DB.OAD_CONZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_DEV_DB.OAD_CONZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_DEV_DB.OAD_RAWZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_DEV_DB.OAD_RAWZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_DEV_DB.OAD_RAWZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_DEV_DB.OAD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_DEV_DB.OAD_TRNZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_DEV_DB.OAD_TRNZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_DEV_DB.OAD_TRNZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_DEV_DB.OAD_TRNZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_SIT_DB.OAD_AUDITZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_SIT_DB.OAD_AUDITZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_SIT_DB.OAD_AUDITZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_SIT_DB.OAD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_SIT_DB.OAD_CONZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_SIT_DB.OAD_CONZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_SIT_DB.OAD_CONZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_SIT_DB.OAD_CONZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_SIT_DB.OAD_RAWZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_SIT_DB.OAD_RAWZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_SIT_DB.OAD_RAWZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_SIT_DB.OAD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_SIT_DB.OAD_TRNZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_SIT_DB.OAD_TRNZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_SIT_DB.OAD_TRNZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_SIT_DB.OAD_TRNZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_UAT_DB.OAD_AUDITZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_UAT_DB.OAD_AUDITZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_UAT_DB.OAD_AUDITZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_UAT_DB.OAD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_UAT_DB.OAD_CONZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_UAT_DB.OAD_CONZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_UAT_DB.OAD_CONZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_UAT_DB.OAD_CONZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_UAT_DB.OAD_RAWZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_UAT_DB.OAD_RAWZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_UAT_DB.OAD_RAWZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_UAT_DB.OAD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_UAT_DB.OAD_TRNZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_UAT_DB.OAD_TRNZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_UAT_DB.OAD_TRNZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_UAT_DB.OAD_TRNZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';


-- CNTRL_REG_PSD_DEV_DB.PSD_AUDITZN_SCM

CREATE OR REPLACE TABLE CNTRL_REG_PSD_DEV_DB.PSD_AUDITZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_DEV_DB.PSD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_DEV_DB.PSD_INTRMZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_DEV_DB.PSD_INTRMZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_DEV_DB.PSD_INTRMZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_DEV_DB.PSD_MARTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_DEV_DB.PSD_MARTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_DEV_DB.PSD_MARTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_DEV_DB.PSD_PRDCTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_DEV_DB.PSD_PRDCTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_DEV_DB.PSD_PRDCTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_DEV_DB.PSD_RAWZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_DEV_DB.PSD_RAWZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_DEV_DB.PSD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_DEV2_DB.PSD_AUDITZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_DEV2_DB.PSD_AUDITZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_DEV2_DB.PSD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_DEV2_DB.PSD_INTRMZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_DEV2_DB.PSD_INTRMZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_DEV2_DB.PSD_INTRMZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_DEV2_DB.PSD_MARTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_DEV2_DB.PSD_MARTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_DEV2_DB.PSD_MARTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_DEV2_DB.PSD_PRDCTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_DEV2_DB.PSD_PRDCTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_DEV2_DB.PSD_PRDCTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_DEV2_DB.PSD_RAWZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_DEV2_DB.PSD_RAWZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_DEV2_DB.PSD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_SIT_DB.PSD_AUDITZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_SIT_DB.PSD_AUDITZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_SIT_DB.PSD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_SIT_DB.PSD_INTRMZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_SIT_DB.PSD_INTRMZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_SIT_DB.PSD_INTRMZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_SIT_DB.PSD_MARTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_SIT_DB.PSD_MARTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_SIT_DB.PSD_MARTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_SIT_DB.PSD_PRDCTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_SIT_DB.PSD_PRDCTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_SIT_DB.PSD_PRDCTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_SIT_DB.PSD_RAWZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_SIT_DB.PSD_RAWZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_SIT_DB.PSD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_SIT2_DB.PSD_AUDITZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_SIT2_DB.PSD_AUDITZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_SIT2_DB.PSD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_SIT2_DB.PSD_INTRMZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_SIT2_DB.PSD_INTRMZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_SIT2_DB.PSD_INTRMZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_SIT2_DB.PSD_MARTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_SIT2_DB.PSD_MARTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_SIT2_DB.PSD_MARTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_SIT2_DB.PSD_PRDCTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_SIT2_DB.PSD_PRDCTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_SIT2_DB.PSD_PRDCTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_SIT2_DB.PSD_RAWZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_SIT2_DB.PSD_RAWZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_SIT2_DB.PSD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_ST_DB.PSD_AUDITZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_ST_DB.PSD_AUDITZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_ST_DB.PSD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_ST_DB.PSD_INTRMZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_ST_DB.PSD_INTRMZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_ST_DB.PSD_INTRMZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_ST_DB.PSD_MARTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_ST_DB.PSD_MARTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_ST_DB.PSD_MARTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_ST_DB.PSD_PRDCTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_ST_DB.PSD_PRDCTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_ST_DB.PSD_PRDCTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_ST_DB.PSD_RAWZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_ST_DB.PSD_RAWZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_ST_DB.PSD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_UAT_DB.PSD_AUDITZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_UAT_DB.PSD_AUDITZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_UAT_DB.PSD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_UAT_DB.PSD_INTRMZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_UAT_DB.PSD_INTRMZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_UAT_DB.PSD_INTRMZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_UAT_DB.PSD_MARTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_UAT_DB.PSD_MARTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_UAT_DB.PSD_MARTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_UAT_DB.PSD_PRDCTZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_UAT_DB.PSD_PRDCTZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_UAT_DB.PSD_PRDCTZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_REG_PSD_UAT_DB.PSD_RAWZN_SCM
-- ============================================================================
CREATE OR REPLACE TABLE CNTRL_REG_PSD_UAT_DB.PSD_RAWZN_SCM.SAMPLE_TABLE (
  ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE PROCEDURE CNTRL_REG_PSD_UAT_DB.PSD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';
