
create or replace TABLE CNTRL_ITSS_OAD_DEV_DB.OAD_AUDITZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_DEV_DB.OAD_AUDITZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_DEV_DB.OAD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_DEV_DB.OAD_CONZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_DEV_DB.OAD_CONZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_DEV_DB.OAD_CONZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_DEV_DB.OAD_CONZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_DEV_DB.OAD_RAWZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_DEV_DB.OAD_RAWZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_DEV_DB.OAD_RAWZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_DEV_DB.OAD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_DEV_DB.OAD_TRNZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_DEV_DB.OAD_TRNZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_DEV_DB.OAD_TRNZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_DEV_DB.OAD_TRNZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_SIT_DB.OAD_AUDITZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_SIT_DB.OAD_AUDITZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_SIT_DB.OAD_AUDITZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_SIT_DB.OAD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_SIT_DB.OAD_CONZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_SIT_DB.OAD_CONZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_SIT_DB.OAD_CONZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_SIT_DB.OAD_CONZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_SIT_DB.OAD_RAWZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_SIT_DB.OAD_RAWZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_SIT_DB.OAD_RAWZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_SIT_DB.OAD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_SIT_DB.OAD_TRNZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_SIT_DB.OAD_TRNZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_SIT_DB.OAD_TRNZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_SIT_DB.OAD_TRNZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_UAT_DB.OAD_AUDITZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_UAT_DB.OAD_AUDITZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_UAT_DB.OAD_AUDITZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_UAT_DB.OAD_AUDITZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_UAT_DB.OAD_CONZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_UAT_DB.OAD_CONZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_UAT_DB.OAD_CONZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_UAT_DB.OAD_CONZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_UAT_DB.OAD_RAWZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_UAT_DB.OAD_RAWZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_UAT_DB.OAD_RAWZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_UAT_DB.OAD_RAWZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';

-- ============================================================================
-- CNTRL_ITSS_OAD_UAT_DB.OAD_TRNZN_SCM
-- ============================================================================
create or replace TABLE CNTRL_ITSS_OAD_UAT_DB.OAD_TRNZN_SCM.SAMPLE_TABLE (
	ID NUMBER(38,0), NAME VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE FUNCTION CNTRL_ITSS_OAD_UAT_DB.OAD_TRNZN_SCM.SAMPLE_FUNCTION("VAL" NUMBER(38,0))
RETURNS NUMBER(38,0) LANGUAGE SQL AS 'val * 2';
CREATE OR REPLACE PROCEDURE CNTRL_ITSS_OAD_UAT_DB.OAD_TRNZN_SCM.SAMPLE_PROCEDURE("P_NAME" VARCHAR)
RETURNS VARCHAR LANGUAGE JAVASCRIPT EXECUTE AS OWNER AS 'return P_NAME;';
