CREATE USER RAF_USER
  TYPE = 'PERSON'
  PASSWORD = 'Str0ng@Pass123!'
  LOGIN_NAME = 'raf_user'
  DISPLAY_NAME = 'Rafeek Peediyekkal'
  EMAIL = 'rafeek@example.com'
  DEFAULT_ROLE = COE_SYS_ADMIN
  DEFAULT_WAREHOUSE = LOAD_WH
  MUST_CHANGE_PASSWORD = FALSE;

  CREATE ROLE streamlit_viewer;

-- Grant minimum required privileges
GRANT USAGE ON DATABASE meta_data_db TO ROLE streamlit_viewer;
GRANT USAGE ON SCHEMA meta_data_db.tables_schema TO ROLE streamlit_viewer;
GRANT USAGE ON STREAMLIT meta_data_db.tables_schema.TENANT_PROJECTS_APP TO ROLE streamlit_viewer;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE streamlit_viewer;

grant ROLE streamlit_viewer to user RAF_USER;


-- Create Databases and schema
CREATE DATABASE IF NOT EXISTS CNTRL_ITSS_OAD_DEV_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_ITSS_OAD_SIT_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_ITSS_OAD_UAT_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_PSD_DEV2_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_PSD_DEV_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_PSD_SIT2_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_PSD_SIT_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_PSD_ST_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_PSD_UAT_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_RDS_DEV2_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_RDS_DEV_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_RDS_SIT2_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_RDS_SIT_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_RDS_ST_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_REG_RDS_UAT_DB;
CREATE DATABASE IF NOT EXISTS CNTRL_TRS_SECURITIZATION_DEV_DB;
CREATE DATABASE IF NOT EXISTS COE_ADMIN_DB;
CREATE DATABASE IF NOT EXISTS COE_CCR_DB;
CREATE DATABASE IF NOT EXISTS COE_CCR_DEV_DB;
CREATE DATABASE IF NOT EXISTS COE_CCR_NPD1_DB;
CREATE DATABASE IF NOT EXISTS COE_CCR_NPD_DB;
CREATE DATABASE IF NOT EXISTS COE_DATA_LAB;
CREATE DATABASE IF NOT EXISTS COE_LRQ_DB;
CREATE DATABASE IF NOT EXISTS COE_LRQ_NPD_DB;
CREATE DATABASE IF NOT EXISTS RTL_DTP_DEV_DB;
CREATE DATABASE IF NOT EXISTS RTL_DTP_SIT_DB;
CREATE DATABASE IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB;
CREATE DATABASE IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB;
CREATE DATABASE IF NOT EXISTS RTL_MTR_REMHUB_ST_DB;

-- Create Schemas
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_DEV_DB.OAD_AUDITZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_DEV_DB.OAD_CONZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_DEV_DB.OAD_RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_DEV_DB.OAD_TRNZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_SIT_DB.OAD_AUDITZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_SIT_DB.OAD_CONZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_SIT_DB.OAD_RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_SIT_DB.OAD_TRNZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_UAT_DB.OAD_AUDITZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_UAT_DB.OAD_CONZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_UAT_DB.OAD_RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_ITSS_OAD_UAT_DB.OAD_TRNZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV2_DB.PSD_AUDITZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV2_DB.PSD_INTRMZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV2_DB.PSD_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV2_DB.PSD_PRDCTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV2_DB.PSD_RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.AUDITZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.DUMMY_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.INTRMZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.PRDCTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.PSD_AUDITZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.PSD_DUMMY_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.PSD_INTRMZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.PSD_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.PSD_PRDCTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.PSD_RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_DEV_DB.RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT2_DB.PSD_AUDITZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT2_DB.PSD_INTRMZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT2_DB.PSD_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT2_DB.PSD_PRDCTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT2_DB.PSD_RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT_DB.PSD_AUDITZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT_DB.PSD_DUMMY_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT_DB.PSD_INTRMZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT_DB.PSD_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT_DB.PSD_PRDCTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_SIT_DB.PSD_RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_ST_DB.PSD_AUDITZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_ST_DB.PSD_DUMMY_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_ST_DB.PSD_INTRMZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_ST_DB.PSD_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_ST_DB.PSD_PRDCTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_ST_DB.PSD_RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_UAT_DB.PSD_AUDITZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_UAT_DB.PSD_INTRMZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_UAT_DB.PSD_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_UAT_DB.PSD_PRDCTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_PSD_UAT_DB.PSD_RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_DEV2_DB.RDS_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_DEV2_DB.RDS_REFZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_DEV_DB.RDS_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_DEV_DB.RDS_REFZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_SIT2_DB.RDS_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_SIT2_DB.RDS_REFZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_SIT_DB.RDS_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_SIT_DB.RDS_REFZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_ST_DB.RDS_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_ST_DB.RDS_REFZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_UAT_DB.RDS_MARTZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_REG_RDS_UAT_DB.RDS_REFZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_TRS_SECURITIZATION_DEV_DB.MAIN;
CREATE SCHEMA IF NOT EXISTS CNTRL_TRS_SECURITIZATION_DEV_DB.RAW;
CREATE SCHEMA IF NOT EXISTS CNTRL_TRS_SECURITIZATION_DEV_DB.SECURITIZATION_MAIN;
CREATE SCHEMA IF NOT EXISTS CNTRL_TRS_SECURITIZATION_DEV_DB.SECURITIZATION_MAINZN_SCM;
CREATE SCHEMA IF NOT EXISTS CNTRL_TRS_SECURITIZATION_DEV_DB.SECURITIZATION_RAW;
CREATE SCHEMA IF NOT EXISTS CNTRL_TRS_SECURITIZATION_DEV_DB.SECURITIZATION_RAWZN_SCM;
CREATE SCHEMA IF NOT EXISTS COE_ADMIN_DB.ACCOUNT_USAGE_BKP;
CREATE SCHEMA IF NOT EXISTS COE_ADMIN_DB.COE_ADMIN_DB_SCHM;
CREATE SCHEMA IF NOT EXISTS COE_CCR_DB.COE_CCR_SCHM;
CREATE SCHEMA IF NOT EXISTS COE_CCR_DEV_DB.COE_CCR_DEV_SCM;
CREATE SCHEMA IF NOT EXISTS COE_CCR_NPD1_DB.COE_CCR_NPD1_SCM;
CREATE SCHEMA IF NOT EXISTS COE_CCR_NPD_DB.COE_CCR_NPD_SCM;
CREATE SCHEMA IF NOT EXISTS COE_DATA_LAB.COE_LAB_SCHM;
CREATE SCHEMA IF NOT EXISTS COE_LRQ_DB.COE_LRQ_SCM;
CREATE SCHEMA IF NOT EXISTS COE_LRQ_NPD_DB.COE_LRQ_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_DTP_DEV_DB.RTL_PSAM_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_DTP_SIT_DB.RTL_PSAM_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_BPO_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_CTL_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_OPS_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_OUTBOUND_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_OUTSYS_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_PLAYPEN_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_RAW_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_REM_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_REP_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_TFM_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_DEV_DB.REMHUB_UTL_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB.REMHUB_BPO_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB.REMHUB_CTL_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB.REMHUB_OPS_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB.REMHUB_OUTSYS_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB.REMHUB_PLAYPEN_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB.REMHUB_RAW_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB.REMHUB_REM_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB.REMHUB_REP_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB.REMHUB_TFM_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_SIT_DB.REMHUB_UTL_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_ST_DB.REMHUB_BPO_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_ST_DB.REMHUB_CTL_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_ST_DB.REMHUB_OPS_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_ST_DB.REMHUB_OUTSYS_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_ST_DB.REMHUB_PLAYPEN_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_ST_DB.REMHUB_RAW_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_ST_DB.REMHUB_REM_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_ST_DB.REMHUB_REP_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_ST_DB.REMHUB_TFM_SCM;
CREATE SCHEMA IF NOT EXISTS RTL_MTR_REMHUB_ST_DB.REMHUB_UTL_SCM;
