-- DDL for META_DATA_DB tables including TENANT_PROJECTS and ACCESS_REQUEST
-- Co-authored with CoCo
CREATE DATABASE IF NOT EXISTS META_DATA_DB;

CREATE SCHEMA IF NOT EXISTS META_DATA_DB.TABLES_SCHEMA;




CREATE TABLE IF NOT EXISTS META_DATA_DB.TABLES_SCHEMA.TENANT_PROJECTS (
    TENANT VARCHAR,
    SUBTENANT VARCHAR,
    PROJECT VARCHAR
);

INSERT INTO META_DATA_DB.TABLES_SCHEMA.TENANT_PROJECTS (TENANT, SUBTENANT, PROJECT)
VALUES
    ('Central[CNTRL]', 'ITSS', 'Purview'),
    ('Central[CNTRL]', 'ITSM', 'OAD'),
    ('Central[CNTRL]', 'REG', 'PSD'),
    ('Central[CNTRL]', 'REG', 'ODS'),
    ('Retail[RTL]', 'CBMFL[MTR]', 'REMHUB'),
    ('Commercial', 'CBAFL', 'CBAFAL'),
    ('Central[CNTRL]', 'TRS', 'Securitization');

CREATE TABLE IF NOT EXISTS META_DATA_DB.TABLES_SCHEMA.ACCESS_REQUEST (
    TENANT VARCHAR,
    SUBTENANT VARCHAR,
    PROJECT VARCHAR,
    REQUEST_TYPE VARCHAR,
    USER VARCHAR,
    ENVIRONMENT VARCHAR,
    SCHEMA VARCHAR DEFAULT 'NA',
    OBJECTS VARCHAR DEFAULT 'NA',
    OBJECT_NAMES VARCHAR DEFAULT 'NA',
    INSERT_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
