-- DDL for META_DATA_DB tables including TENANT_PROJECTS and ACCESS_REQUEST
-- Co-authored with CoCo
CREATE DATABASE IF NOT EXISTS META_DATA_DB;
CREATE SCHEMA IF NOT EXISTS META_DATA_DB.TABLES_SCHEMA;
CREATE TABLE IF NOT EXISTS META_DATA_DB.TABLES_SCHEMA.TENANT_PROJECTS (
    TENANT VARCHAR,
    SUBTENANT VARCHAR,
    PROJECT VARCHAR
);

INSERT INTO META_DATA_DB.TABLES_SCHEMA.TENANT_PROJECTS (TENANT, SUBTENANT, PROJECT)
VALUES
   ,    ('Central[CNTRL]', 'ITSM', 'OAD'),

    ('Central[CNTRL]', 'REG', 'ODS'),
    ('Retail[RTL]', 'CBMFL[MTR]', 'REMHUB'),
    ('Commercial', 'CBAFL', 'CBAFAL'),
    ('Central[CNTRL]', 'TRS', 'Securitization');

CREATE TABLE IF NOT EXISTS META_DATA_DB.TABLES_SCHEMA.ACCESS_REQUEST (
    TENANT VARCHAR,
    SUBTENANT VARCHAR,
    PROJECT VARCHAR,
    REQUEST_TYPE VARCHAR,
    USER VARCHAR,
    ENVIRONMENT VARCHAR,
    SCHEMA VARCHAR DEFAULT 'NA',
    OBJECTS VARCHAR DEFAULT 'NA',
    OBJECT_NAMES VARCHAR DEFAULT 'NA',
    INSERT_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS META_DATA_DB.TABLES_SCHEMA.APP_PASSWORDS (
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);



INSERT INTO META_DATA_DB.TABLES_SCHEMA.APP_PASSWORDS (USERNAME, PASSWORD_HASH)
SELECT 'admin', SHA2('admin123')

INSERT INTO META_DATA_DB.TABLES_SCHEMA.APP_PASSWORDS (USERNAME, PASSWORD_HASH)
SELECT 'username_here', SHA2('password_here');

UPDATE META_DATA_DB.TABLES_SCHEMA.APP_PASSWORDS
SET PASSWORD_HASH = SHA2('new_password')
WHERE UPPER(USERNAME) = 'ADMIN';


SELECT * FROM 
META_DATA_DB.TABLES_SCHEMA.APP_PASSWORDS