CREATE DATABASE IF NOT EXISTS META_DATA_DB;

CREATE SCHEMA IF NOT EXISTS META_DATA_DB.TABLES_SCHEMA;

CREATE TABLE IF NOT EXISTS META_DATA_DB.TABLES_SCHEMA.TENANT_PROJECTS (
    TENANT VARCHAR,
    SUBTENANT VARCHAR,
    PROJECT VARCHAR
);

INSERT INTO META_DATA_DB.TABLES_SCHEMA.TENANT_PROJECTS (TENANT, SUBTENANT, PROJECT)
VALUES
    ('Central', 'ITSS', 'Purview'),
    ('Central', 'ITSM', 'OAD'),
    ('Central', 'REG', 'PSD'),
    ('Central', 'REG', 'ODS'),
    ('Retail', 'CBMFL', 'REMHUB'),
    ('Commercial', 'CBAFL', 'CBAFAL'),
    ('Central', 'TRS', 'Securitization');
